### ISSUE TITLE
Fork-Rewrite: Progress roadmap

### ISSUE THREAD

**Issue by AgentConDier** [AgentConDier/LRC-Editor#3]
- [ ] Recursive file list
- [ ] Color-coding whether corresponding lrc/mp3/m4a/flac files do or do not exist
- [ ] Go to create screen if lrc missing, editor otherwise
- [ ] Automatic music-file loading in the editor
- [ ] Redesign save screen: 
    - [ ] Correct file path displaying
    - [ ] Ability to select save path manually
    - [ ] Buttons for setting the save path to
        - the location of the lrc file if it was opened from the app or elsewhere
        - match tle music file if lyrics were newly created
- [x] Three decimals after the seconds because Huawei expects this
- [x] Free dark mode

**Comment by Spikatrix** [comment]
First of all, Thank you for contributing to my app.

I'm actually working on a new version of LRC Editor and there are several changes including but not limited to 
- Recursive file list
- Splitting the read and save locations
- Making the code more consistent (as you've seen, my code is a big mess :p) and easier to understand
- Several other changes and bug fixes

I don't have a specific date planned for the release but I'll try to release it soon.

<hr>

In your task list, I'm not sure why you say that "_Three decimals after the seconds because Huawei expects this_". I mean I know that the Huawei player adds a leading zero to the milliseconds when you enter the "Rearrange lyrics" mode from the player using an LRC file with only two digit milliseconds (Xiaomi's player also does this), but it also accepts LRC files with two digit milliseconds, right? So I'm not sure why the change is required (LRC Editor should be able to read both two and three digit milliseconds without issues)

**Comment by AgentConDier** [comment]
Huawei does accept two decimals, but it adds the zero in the wrong place when rearranging lyrics, throwing off the timing: [12:34:56.78] becomes [12:34:56.078] and after editing in the LRC Editor [12:34:56.070]
Update: ~It looks like they fixed this~ No they didn't:
<pre><code>$ cat storage/shared/Musik/Imagine\ Dragons\ -\ Thunder.lrc

[re: LRC Editor - Android app]
[ve: Version 2.2.3]

[00:00.00]
[00:00.12]test
[00:00.20]
$ cat storage/shared/Musik/Imagine\ Dragons\ -\ Thunder.lrc
[re: LRC Editor - Android app]
[ve: Version 2.2.3]
[00:00.000]
[00:00.012]test
[00:00.020]</code></pre>
I'm looking forward to the new version!

**Comment by Spikatrix** [comment]
I see. Xiaomi's music player does insert the zero in the correct place, i.e, at the end of the millisecond. Thanks for the info!

**Comment by Spikatrix** [comment]
I've just released LRC Editor Version 3.0.0. I've made the code so much better and consistent. You should find it much more easier to make changes to it now. 

Thank you for contributing to my app! ツ

**Comment by AgentConDier** [comment]
Closing since I will not work on fork-rewrite any more
