### ISSUE TITLE
Music-Autoload: Progress tracker

### ISSUE THREAD

**Issue by AgentConDier** [AgentConDier/LRC-Editor#4]
- [x] Add intent extra for song uri to EditorActivity
- [ ] Add song auto-discovery functionality to EditorActivity
- [ ] Add related settings (Song directory location, valid audio file types)
- [x] Add lrc uri intent extra to EditorActivity and FinalizeActivity
  - [x] If lrc uri is known, "save" button does not open save location dialog, add "save as" button instead
